### ISSUE TITLE
The JS scripts of the imported page are downloaded every time

### ISSUE THREAD

**Issue by andreadrupal** [AshleyScirra/html-imports-polyfill#2]
Can you confirm that the multiple imports of the same html page imports its scripts many times? I'm looking for a replacement of the standard chrome "HTML IMPORT" that knows if he has already downloaded a script, avoiding to create duplicates.
Thank you

**Comment by AshleyScirra** [comment]
I think imports are deduplicated, but actual scripts are not. It should be easy to test this, just try it.
